### ISSUE TITLE
npm Error when installing citrineOS

### ISSUE THREAD

**Issue by tefelberson** [citrineos/citrineos#22]
Hi everyone!
i'm installing Citrineos , i want to connect it to everest(https://everest.github.io/) but I'm encountering an error when executing "docker-compose up -d" command.
You can capture this screen. 
![Capture d'écran 2024-05-05 103613](https://github.com/citrineos/citrineos/assets/73689893/51580e13-8815-402a-8682-73da4a9fbae3)

I need help please

**Comment by thanaParis** [comment]
Hi @tefelberson !
Here is a stackoverflow page that elaborates on the error you are seeing: https://stackoverflow.com/questions/63010779/npm-err-code-eai-again-error-when-trying-to-install-express
I would suggest trying some of the fixes mentioned there.

**Comment by ChrisWeissmann** [comment]
Hi @tefelberson, did Thana's suggestion resolve the issue for you? Seems it might be due npm running through a proxy and not being able to resolve an address. 
If all is well, can we close this issue?
