### ISSUE TITLE
Unable to start with citrineos-ocpi

### ISSUE THREAD

**Issue by DylanVautrin** [citrineos/citrineos#32]
Hello, 
I'm trying to use the command docker compose -f docker-compose.with.ocpi.yml build but i don't have any file with this name.
I succeed to start it with the classic command , so “without” ocpi part ? 
I'm using last release of core and ocpi.
Thanks for your help !

**Comment by thanaParis** [comment]
Hi Dylan! The default docker compose now also includes ocpi. Thank you for bringing to my attention that the github.io needs correcting.

**Comment by DylanVautrin** [comment]
Oh okay then sorry for this issue !  I think the read-me of citrineos-core can be update too :)
Thanks, i'm closing this.
