### ISSUE TITLE
Why do I get the following error when trying to build? 

### ISSUE THREAD

**Issue by arahman33** [citrineos/citrineos#35]
**Which repository?**
Is it: 
- citrineos-core
- citrineos-ocpi

**Describe the bug**
**00_Base/src/index.ts(12,3): error TS2724: '"@citrineos/data"' has no exported member named 'RepositoryStore'. Did you mean 'Repository'?**

**To Reproduce**
I followed the steps in https://citrineos.github.io/docs/getting-started.html to build.

**Expected behavior**
Successful build

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
1:25:18 AM - Project '../citrineos-core/00_Base/tsconfig.json' is out of date because output file '../citrineos-core/00_Base/tsconfig.tsbuildinfo' does not exist
0.525
0.525 1:25:18 AM - Building project '/usr/local/apps/citrineos-core/00_Base/tsconfig.json'...
0.525
2.873 1:25:20 AM - Project '../citrineos-core/01_Data/tsconfig.json' is out of date because output file '../citrineos-core/01_Data/tsconfig.tsbuildinfo' does not exist
2.873
2.873 1:25:20 AM - Building project '/usr/local/apps/citrineos-core/01_Data/tsconfig.json'...
2.873
4.134 1:25:21 AM - Project '00_Base/tsconfig.json' is out of date because output file '00_Base/tsconfig.tsbuildinfo' does not exist
4.134
4.134 1:25:21 AM - Building project '/usr/local/apps/citrineos-ocpi/00_Base/tsconfig.json'...
4.134
5.624 00_Base/src/index.ts(12,3): error TS2724: '"@citrineos/data"' has no exported member named 'RepositoryStore'. Did you mean 'Repository'?
5.641 1:25:23 AM - Project '../citrineos-core/02_Util/tsconfig.json' is out of date because output file '../citrineos-core/02_Util/tsconfig.tsbuildinfo' does not exist
5.641
5.641 1:25:23 AM - Building project '/usr/local/apps/citrineos-core/02_Util/tsconfig.json'...
5.641
8.171 1:25:25 AM - Project '03_Modules/Versions/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.171
8.171 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Versions/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.171
8.171 1:25:25 AM - Project '03_Modules/Cdrs/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.171
8.171 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Cdrs/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.171
8.171 1:25:25 AM - Project '03_Modules/Credentials/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.171
8.171 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Credentials/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.171
8.171 1:25:25 AM - Project '03_Modules/Commands/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.171
8.171 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Commands/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.171
8.171 1:25:25 AM - Project '03_Modules/ChargingProfiles/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.171
8.171 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/ChargingProfiles/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.171
8.172 1:25:25 AM - Project '03_Modules/Locations/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.172
8.172 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Locations/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.172
8.172 1:25:25 AM - Project '03_Modules/Sessions/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.172
8.172 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Sessions/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.172
8.172 1:25:25 AM - Project '03_Modules/Tariffs/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.172
8.172 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Tariffs/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.172
8.172 1:25:25 AM - Project '03_Modules/Tokens/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.172
8.172 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/03_Modules/Tokens/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.172
8.172 1:25:25 AM - Project 'Server/tsconfig.json' can't be built because its dependency '00_Base' has errors
8.172
8.172 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/Server/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/00_Base' has errors
8.172
8.173 1:25:25 AM - Project 'tsconfig.json' can't be built because its dependency 'Server' was not built
8.173
8.173 1:25:25 AM - Skipping build of project '/usr/local/apps/citrineos-ocpi/tsconfig.json' because its dependency '/usr/local/apps/citrineos-ocpi/Server' was not built
8.173
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2

**Comment by yuvenus** [comment]
Hello @arahman33! I've found that when I get a build issue like this, following these steps resolves the issue:

1. Checkout and pull `main` branch in `citrineos-core`
2. Run `npm run fresh-and-install-all` in the root of `citrineos-core`
3. Checkout and pull `main` branch in `citrineos-ocpi`
4. Run `npm run fresh-and-install-all` in the root of `citrineos-ocpi`
5. In `citrineos-core`, go to the `Server` folder
6. Run the `docker compose up -d` command

Please give these steps a try and let me know if you have any more questions, thank you!
