### ISSUE TITLE
No Error Response for Invalid OCPP Message[citrineos-core]

### ISSUE THREAD

**Issue by jongchan988** [citrineos/citrineos#41]
**Which repository?**
Is it:
- citrineos-core

**Describe the bug**

When sending an OCPP BootNotification request with an incorrect field (e.g., a typo in the "reason" field), there is no response from the server. A proper error response is expected but not received.

**To Reproduce**
Connect to the WebSocket server at ws://localhost:8081/CHARGER02.
Send the following OCPP BootNotification request with a typo in the "reason" field:
![image](https://github.com/user-attachments/assets/e1587948-b0ef-4d6a-a049-4da05592d36c)

**Expected behavior**
The server should have returned an OCPP error response but did not.

From the Docker logs, I found the following related information but don't send expect response
![image](https://github.com/user-attachments/assets/92701c7d-a13a-4bbf-9539-5657b44e21e9)

**Comment by thanaParis** [comment]
This has been fixed as of 1.4.3! Thank you for reporting!!
