### ISSUE TITLE
Incomplete OpenAPI specification [citrineos-core]

### ISSUE THREAD

**Issue by jacoblu** [citrineos/citrineos#49]
**Which repository?**
- citrineos-core

**Describe the bug**
The generated OpenAPI specification (available at `/docs/json`) is missing type definitions for request bodies and any definitions for response bodies.

***Request bodies***
The requests defined in the specification make references to the types expected in the request body using the `$ref` keyword but the actual definitions are missing from the specification.

***Response bodies***
All responses in the generated specification are defined identically, a 200 empty response. This is probably correct for some requests but many actually return something.

**To Reproduce**
Tested on latest main (commit f0bda14)
1. Go to `{REPO_ROOT_DIR}/Server`
2. Build and run Docker containers with `> docker-compose -f .\docker-compose.yml up -d --build`
3. Open [http://localhost:8080/docs/json](http://localhost:8080/docs/json) in browser
4. See the following errors in generated OpenAPI specification:
    - No types defined in `components.schemas`
    - No `responses` are defined to actually return any values
    
The errors can also be shown by checking the hosted SwaggerUI while the Citrine server Docker container is running, for instance at  [http://localhost:8080/docs/static/index.html#/null/put_data_evdriver_authorization](http://localhost:8080/docs/static/index.html#/null/put_data_evdriver_authorization)

**Expected behavior**
The generated OpenAPI specification should completely describe the hosted API, including request parameters+bodies as well as the data returned by those requests. It should also include the definitions for all types referenced in the document.

**Screenshots**
***Request bodies***
Example type reference in request body
![image](https://github.com/user-attachments/assets/5c354074-966b-4813-91ed-1075ecb0f55b)

Referenced path in generated OpenApi specification
![image](https://github.com/user-attachments/assets/518e0cdb-6678-466f-8d09-115845c46aad)

***Response bodies***
Example missing response body
![image](https://github.com/user-attachments/assets/c6487155-faf0-49f9-a8ba-9c7661de9ca0)

**Desktop (please complete the following information):**
 - OS: OS: Windows 11, WSL2 with docker

**Comment by elliot-sabitov** [comment]
Hi @jacoblu,

Thank you so much for creating this issue! 

Please note that this PR was created to include type definitions in the OpenAPI spec - https://github.com/citrineos/citrineos-core/pull/289

**Comment by elliot-sabitov** [comment]
Please note that there was an additional PR to address an issue where Directus Flows were not generating properly after merging https://github.com/citrineos/citrineos-core/pull/289 which was resolved in https://github.com/citrineos/citrineos-core/pull/294
